# docker-compose.dev.yml
version: '3'

services:
  nextjs-dashboard:
    container_name: nextjs-dashboard-postgres
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    # Set environment variables based on the .env file
    env_file:
      - .env
    # Set environment variables directly in the docker-compose file
    environment:
      POSTGRES_ADDR: postgres
      POSTGRES_DATABASE: nextjs-dashboard-postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app/next-app
    restart: always
    ports:
      - 3000:3000
  postgres:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "postgres", "-d", "nextjs-dashboard-postgres"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  pgdata: {}